name: StandardRB

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: StandardRB Linter
      uses: uiuuiu/standardrb-action@1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}









        